name: 'test'

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        environment: [ci-sklearn12, ci-sklearn13, ci-sklearn14, ci-sklearn15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.36.0
          environments: ${{ matrix.environment }}
          # we can freeze the environment and manually bump the dependencies to the
          # latest version time to time.
          frozen: true

      - name: Run tests
        run: pixi run -e ${{ matrix.environment }} tests -n 3

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: glemaitre/sklearn_compat
